### ISSUE TITLE
部署好后报错

### ISSUE THREAD

**Issue by onion0835** [yingshang/feishu-talk#2]
![image](https://user-images.githubusercontent.com/24467503/232442795-8e2dd1bf-b97c-48f8-8926-a6cabcd695db.png)
[2023-04-17 17:23:33,080] ERROR in app: Exception on /feishu/callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/root/feishu-talk/app.py", line 171, in callback_event_handler
    return event_handler(event)
  File "/root/feishu-talk/app.py", line 122, in message_receive_event_handler
    sougou_generate_audio(resp_text,filepath2)
  File "/root/feishu-talk/core/generate_audio.py", line 23, in sougou_generate_audio
    audio = AudioSegment.from_file(audio_data, format="mp3")
  File "/usr/local/lib/python3.8/dist-packages/pydub/audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
  File "/usr/local/lib/python3.8/dist-packages/pydub/utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe'

**Comment by yingshang** [comment]
apt install -y ffmpeg
要装下这个

**Comment by onion0835** [comment]
[2023-04-18 08:41:18,969] ERROR in app: Exception on /feishu/callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/root/feishu-talk/app.py", line 171, in callback_event_handler
    return event_handler(event)
  File "/root/feishu-talk/app.py", line 123, in message_receive_event_handler
    filekey = message_api_client.upload_audio_file(filepath2)
  File "/root/feishu-talk/core/api.py", line 66, in upload_audio_file
    file_key = response.json()['data']['file_key']
KeyError: 'data'

发现这个错误，是飞书后台  权限设置的不对么？

**Comment by yingshang** [comment]
权限搜索`drive:`、`im:resource`、`chat:`，把这些批量开通试试
![image](https://user-images.githubusercontent.com/11006249/232647539-fb427e59-5434-4b3c-b6ec-76f1bd4d30ab.png)

**Comment by onion0835** [comment]
权限我都打开了，还是在这个错误呢

**Comment by onion0835** [comment]
root@VM-0-7-ubuntu:~/feishu-talk/chatfile# ll
total 548
drwxr-xr-x 2 root root   4096 Apr 18 10:16 ./
drwxr-xr-x 8 root root   4096 Apr 18 10:19 ../
-rw-r--r-- 1 root root 106028 Apr 18 08:41 2023-04-18_08-41-15.wav
-rw-r--r-- 1 root root 106028 Apr 18 10:15 2023-04-18_10-15-00.wav
-rw-r--r-- 1 root root 328364 Apr 18 10:16 2023-04-18_10-15-59.wav
-rw-r--r-- 1 root root   5540 Apr 18 10:16 audio_2023-04-18_10-16-00.mp3
文件都已经传到服务器上来了，是不是调用接口失败？

**Comment by yingshang** [comment]
你有用腾讯的ASR的key解析语音吗？如果没有的话，你就直接用飞书语音转文字就行

**Comment by onion0835** [comment]
我是在python3.8下运行的，你的运行环境是什么？我有腾讯ASR的key

**Comment by yingshang** [comment]
python3.7，不影响的，你可以直接用dockerfile构建镜像

**Comment by onion0835** [comment]
我跟踪到是到这里报的错误：
    def upload_audio_file(self,filepath):
        self._authorize_tenant_access_token()
        filename = filepath.split("/")[-1]
        # 请注意使用时替换文件path和Authorization
        url = "https://open.feishu.cn/open-apis/im/v1/files"
        form = {'file_type': 'opus',
                'file_name': filename,
                'file': (filename, open(filepath, 'rb'),'text/plain')
                }  # 需要替换具体的path  具体的格式参考  https://www.w3school.com.cn/media/media_mimeref.asp
        multi_form = MultipartEncoder(form)
        headers = {
            "Authorization": "Bearer " + self.tenant_access_token
        }
        headers['Content-Type'] = multi_form.content_type
        print(url)
        **response = requests.request("POST", url, headers=headers, data=multi_form)**
        print(response)
        file_key = response.json()['data']['file_key']
        return file_key

[2023-04-18 13:14:24,627] ERROR in app: Exception on /feishu/callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/root/feishu-talk/app.py", line 172, in callback_event_handler
    return event_handler(event)
  File "/root/feishu-talk/app.py", line 124, in message_receive_event_handler
    filekey = message_api_client.upload_audio_file(filepath2)
  File "/root/feishu-talk/core/api.py", line 66, in upload_audio_file
    response = requests.request("POST", url, headers=headers, data=multi_form)
KeyError: 'data'  

这里难道是因为multi_form 是空？

**Comment by yingshang** [comment]
你
print(form)
print(response.text)
看看，感觉你没有开启飞书上传文件接口的权限

**Comment by yingshang** [comment]
https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/file/create

**Comment by yingshang** [comment]
![image](https://user-images.githubusercontent.com/11006249/232685412-14b4f83c-d6a9-40cf-917e-01d2cacd038c.png)

**Comment by onion0835** [comment]
确实 增加权限后可以了，谢啦，我下载了生成的语音，效果还可以，能换成微软Azure的 tts接口么？

**Comment by yingshang** [comment]
在开发中，明天或者后天

**Comment by yingshang** [comment]
写好了，你修改下config.py配置文件，配置完成后，可以在飞书输入以下内容，就可以生成音频
英文播放
The term "synonymous" is often used in discussions of language, and it refers to words that have a similar or identical meaning. In other words, if two words are synonymous, they can be used interchangeably in certain contexts without changing the meaning of a sentence. However, it's important to note that not all words are completely synonymous; sometimes there are subtle differences in their connotations or usage that can affect the overall meaning of a sentence. For example, the words "happy" and "joyful" are often considered synonymous, but "joyful" suggests a deeper, more sustained feeling of happiness than "happy" does. When using synonyms, it's important to be aware of these nuances in order to communicate effectively.

**Comment by onion0835** [comment]
怎么配置能实现把录入的英文变成 生成音频呢？
我刚才试了一下，还是返回的chatgpt的回答啊

**Comment by yingshang** [comment]
你看看文档，里面有演示

**Comment by onion0835** [comment]
![微信图片_20230419125726](https://user-images.githubusercontent.com/24467503/232970906-0cc5b051-2d08-4a57-a369-6ee3de96e48b.jpg)
词汇阅读和词汇题不好用呢,我更新了单词后，没有输出

**Comment by yingshang** [comment]
词汇题的prompt还没有写好，你是不是录入单词少于10个，我是随机抽取10个，可以在config.py配置
![image](https://user-images.githubusercontent.com/11006249/232975406-77ec9ed5-ed52-4cb1-b88a-9496696e1f69.png)

**Comment by onion0835** [comment]
还有个问题，能不能设置一下 口语回复内容的难度？

**Comment by yingshang** [comment]
这个是prompt的问题，你可以提供相应的难度prompt给我，我来加

**Comment by onion0835** [comment]
能不能提供这样的功能，例子是这样的：
开始对话
food

然后就开始关于food的对话，采用下面的prompt   ：Let's have a back-and-forth conversation about food? before you respond please first correct any mistakes you noticed in what I said and provide me with alternative ways of expressing my idea.

然后如果回复别的主题词，替换掉里面的food 就可以了

**Comment by yingshang** [comment]
这个prompt还是会让AI疑惑
As an AI
 language model, I cannot correct mistakes in your conversation beforehand. However, I can certainly engage in a back-and-forth conversation with you abou
t food. So, what dish or type of food do you like the most?

**Comment by yingshang** [comment]
我等会写一个语法批改，在你发送语音后，飞书会回复两个信息给你，一个是你口语的语法，一个是AI的回复

**Comment by yingshang** [comment]
好了，已经完成了，你看下文档吧

**Comment by onion0835** [comment]
业界良心就是你了
